apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ts-activity.fullname" . }}
  labels:
    {{- include "ts-activity.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ts-activity.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ts-activity.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ts-activity.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TS_DISCORD_USERNAME
              value: "{{ .Values.config.discordUsername | default "Jeff" }}"
            - name: TS_QUERY_ADDR
              value: "{{ .Values.config.serverQueryAddr | required "must provide serverQueryAddr" }}"
            - name: TS_QUERY_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: "{{ .Values.config.serverQuerySecret | required "must provide serverQuerySecret" }}"
            - name: TS_QUERY_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: "{{ .Values.config.serverQuerySecret | required "must provide serverQuerySecret" }}"
            - name: TS_DISCORD_WEBHOOK
              valueFrom:
                secretKeyRef:
                  key: discord
                  name: "{{ .Values.config.webhookSecret | required "must provide webhookSecret" }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
