on: [push, pull_request]

name: Build

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: false
          tags: dev
